### PR TITLE
stamp.statics() 2.0

### PR DESCRIPTION
**Pull request by troutowicz**
Relates to issue #64 

- [x] set using factory arg
- [x] set using factory method
- [x] set/override using factory method chaining
- [x] set/override using stamp composition

I'm not sure on the convenience method name, would `static` be better?

One use case that will fail is composition with a stamp that is extended with an object of functions.

```js
var stamp = stampit.extend(stampit(), {
  foo: function () {
    return 'foo';
  }
});
```

The `fixed.statics` property does not get set in this case, resulting in the `foo` method being undefined.

### CODE REVIEW

**Comment by ericelliott** [comment]
I'd prefer the singular, `static` (short for "static properties").

We'll also want to add documentation. =)

**Comment by koresar** [comment]
If we merge this then stampit v1 and v2 will have different fourth parameter. Moreover, this PR lacks tests. I'd implement this feature in v2 which I'm going to finish today. :)

**Comment by troutowicz** [comment]
@koresar It was decided in #64 that v1 should only get the method form of this feature.

I can probably write up the tests in the next 24 hours, I got sidetracked with #66 today.

**Comment by koresar** [comment]
I somehow missed the decision taking message.

So, method is the only thing implemented. The fourth parameter for `stampit()` will not be implemented. Is that correct?

Also README better be updated I reckon.

What if someone would like to create a static called "state" or "compose" or "methods"?
```js
var stamp = stampit().static({ compose: () => { console.log('hello'); });
stamp.compose ... ?
```
We should warn people that using reserved function names may and will lead to conflicts and unpredicted behaviours. Any ideas?

**Comment by koresar** [comment]
One more thing.

You might want to consider `converConstructor` statics support. See the sample unit test:
```js
export class Counter extends React.Component {
  static defaultProps = { initialCount: 42 };
}

var stamp = stampit.convertConstructor(Counter);
assert(stamp.propTypes.initialCount === 42);
```

**Comment by ericelliott** [comment]
> So, method is the only thing implemented. The fourth parameter for stampit() will not be implemented. Is that correct?

True for v1. For v2 I'd like to see all params collapsed into a single options arg, where `static` will be available.

**Comment by ericelliott** [comment]
> You might want to consider converConstructor statics support. See the sample unit test:

:+1:

**Comment by troutowicz** [comment]
From what I've experienced, stampit is not compatible with ES6 classes.

https://github.com/babel/babel/issues/682

**Comment by ericelliott** [comment]
> stampit is not compatible with ES6 classes

Can you write a test that demonstrates the problem with Stampit, specifically?

**Comment by troutowicz** [comment]
```js
test('stamp from ES6 class', (t) => {
  t.plan(1);

  class Foo {}
  const fooStamp = stampit.convertConstructor(Foo);

  t.ok(
    stampit.compose(fooStamp)(),
    'should create instance'
  );
});
```

`TypeError: Cannot call a class as a function`

**Comment by ericelliott** [comment]
Could you file that as a bug in a new issue?

**Comment by troutowicz** [comment]
Sure. #75

**Comment by troutowicz** [comment]
I am going to create another PR for the 1.x branch. @ericelliott I know you prefer `static` over `statics`, however jshint will puke complaining about `static` and it being a reserved keyword. Do we disable jshint reserved keyword checks?

**Comment by koresar** [comment]
I'll reimplement this in v2.0 branch after we merge #76 to v1, and #72 to v2. The idea and approach will be reused of course.

This PR is too incompatible. Easier to (re)implement than to merge. I can do that hopefully this week.  I'd close this PR for now. Are you alright with that @troutowicz?

Sorry I can't get free much time lately.

**Comment by troutowicz** [comment]
I'll close it for you :)

**Comment by koresar** [comment]
Cheers @troutowicz :)

**Pull request closed without merging**
