### PR TITLE
port tests to tape

### PR DESCRIPTION
**Pull request by JosephClay**
See #61

### CODE REVIEW

**Comment by koresar** [comment]
Hey, thank you mate!

I wish you could start from #56 so that these changes could be already tested by Travis.

We are going to have multiple merge conflicts as I have changed the tests significantly here: #60 
Also, I migrated to lodash the entire codebase in the same PR. I should have fixed and merged my branch earlier so that you could migrate to tape the latest code base. Sorry for that.

There are not many changes in this PR, though. Thus, I'll merge it after #60 if that's okay.

How do you feel of implementing #56 (add the `.travis.yml`)?

**Comment by JosephClay** [comment]
Merge away.

I'll try my hand at #56 ...what's the worst that can happen?

**Comment by koresar** [comment]
:) I hope nothing bad will happen after adding a single file.

**Comment by JosephClay** [comment]
I added the .travis.yml and configured `npm test` to run the tape tests. Travis will still need to be setup via [sign in and webhooks](http://docs.travis-ci.com/user/getting-started/#Step-one%3A-Sign-in).

In order for browserify/tape-run to work (and not conflict with grunt-browserify), I moved the grunt tasks to npm scripts. I have left the gruntfile and test html file in the project for posterity, as it has the saucelabs configuration. 

Is the intent to get both travis and sauce integrated? If not, I can remove a couple more files.

**Comment by ericelliott** [comment]
Eventually I'd like to get Sauce Labs tests working, but go ahead and delete the files you don't need. We can recover old settings from version control if we need them.

Since there is a new version of Sauce Connect with breaking changes, I don't think the old settings would be useful anymore, anyway. =)

**Comment by JosephClay** [comment]
Done

**Comment by ericelliott** [comment]
@koresar if you can review this and merge, I'll be happy to set up the Travis CI GitHub integration.

**Comment by koresar** [comment]
Let me check all the things on Sunday (American Saturday ☺). Sorry for
inconvenience. The life is busy recently.

**Comment by ericelliott** [comment]
No worries. I'm just glad you're willing to help. =)

**Comment by koresar** [comment]
Merged to v2_0.

**Pull request merged**
