### PR TITLE
init tests

### PR DESCRIPTION
**Pull request by unstoppablecarl**
added test for order init functions are called
added test for stamp and opts.instace match

### CODE REVIEW

**Comment by ericelliott** [comment]
Looks good to me. I don't have time to pull it down and test it myself.

@koresar @troutowicz - feel free to merge if you beat me to it. =)

Maybe I shouldn't be allowed to merge this week. Crazy busy and distracted.

**Comment by troutowicz** [comment]
Thanks @unstoppablecarl

**Comment by ericelliott** [comment]
@unstoppablecarl I've made you a repo collaborator, which means you can merge PRs from fellow collaborators. Please continue to use the PR process for contributions. =)

**Comment by koresar** [comment]
Ah, the missing tests. Thanks Carl.

**Pull request merged**
